# Site settings
title: 'Muhammad Ibnuh'
description: 'Web developer. Specializes in backend-development, Appreciate clean and clear code. Having strong skills to develop perfect solutions for complex logic using newest technologies.'
url: 'https://ibnuhx.com'

# Author
author:
    name: Muhammad Ibnuh
    url: https://ibnuhx.com
    email: ibnuhdev@gmail.com
    github: https://github.com/ibnuh

twitter:
    username: ibnuhx
    card: summary

# Build settings
markdown: kramdown

# Assets
sass:
    sass_dir: _sass
    style: compressed

# Gems
plugins:
    - jekyll-feed
    - jekyll-paginate
    - jekyll-seo-tag
    - jekyll-sitemap

# Permalinks
permalink: /:title
paginate: 6

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
        envs: []
    blanklines: false
    profile: false
    startings: []

collections:
    topics:
        output: true
        permalink: topics/:path
