# Site settings
title: 'Muhammad Ibnuh'
description: 'Web developer. Specializes in backend-development, Appreciate clean and clear code. Having strong skills to develop perfect solutions for complex logic using newest technologies.'
url: 'https://muhammadibnuh.com'

# Author
author:
    name: Muhammad Ibnuh
    url: https://muhammadibnuh.com
    email: ibnuhdev@gmail.com

# Build settings
markdown: kramdown

# Assets
sass:
    sass_dir: _sass
    style: compressed

# Gems
plugins:
    - jekyll-feed
    - jekyll-paginate
    # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink: /:title
paginate: 5

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
        envs: []
    blanklines: false
    profile: false
    startings: []
